version: '3.9'
services:
  APP_NAME:
    container_name: APP_NAME
    image: 'registry.richardx.win/APP_NAME:latest'
    restart: unless-stopped
    ports:
      - '3005'
    labels:
      - traefik.enable=true
      - traefik.http.routers.APP_NAME.rule=Host(`APP_NAME.richardx.win`)
    environment:
      - KEY=$KEY

networks:
  default:
    name: proxy
    external: true
