version: '3.9'
services:
  appin:
    container_name: appin
    image: 'registry.richardxiong.com/appin:latest'
    restart: unless-stopped
    ports:
      - '3005'
    labels:
      - traefik.enable=true
      - traefik.http.routers.appin.rule=Host(`appin.richardxiong.com`)
    environment:
      - DATABASE_URL=$DATABASE_URL
      - JWT_SECRET=$JWT_SECRET
      - ADMIN_PASSWORD=$ADMIN_PASSWORD

networks:
  default:
    name: proxy
    external: true
